# Generated by Django 5.2.6 on 2026-01-12 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#00d4ff', help_text='Hex color code (e.g., #00d4ff)', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(choices=[('technical', 'Technical Support'), ('billing', 'Billing & Account'), ('sales', 'Sales Inquiry'), ('enterprise', 'Enterprise Plan'), ('partnership', 'Partnership Opportunity'), ('security', 'Security Concern'), ('feedback', 'Product Feedback'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('is_priority', models.BooleanField(default=False)),
                ('subscribe_newsletter', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.contacttag')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submission_date', 'priority'],
                'indexes': [models.Index(fields=['status', 'priority'], name='core_contac_status_19aa2c_idx'), models.Index(fields=['email'], name='core_contac_email_44c0bc_idx'), models.Index(fields=['submission_date'], name='core_contac_submiss_d6b85b_idx')],
            },
        ),
    ]
