# Generated by Django 5.2.10 on 2026-01-19 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('oauth_connect', 'OAuth Connection'), ('oauth_disconnect', 'OAuth Disconnect'), ('2fa_enable', '2FA Enabled'), ('2fa_disable', '2FA Disabled'), ('2fa_verify', '2FA Verification'), ('google_api', 'Google API Call'), ('github_api', 'GitHub API Call'), ('account_sync', 'Account Sync'), ('security_check', 'Security Check'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated')], max_length=50)),
                ('service', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('authflowx', 'AuthFlowX'), ('system', 'System')], default='authflowx', max_length=20)),
                ('description', models.TextField()),
                ('account_email', models.CharField(blank=True, max_length=255, null=True)),
                ('account_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'), models.Index(fields=['action_type', 'created_at'], name='core_activi_action__e16858_idx')],
            },
        ),
    ]
