# Generated by Django 5.2.10 on 2026-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='account_provider',
            field=models.CharField(default='AuthFlowX', max_length=50),
        ),
    ]
