# Generated by Django 6.0.3 on 2026-03-15 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('python_version', models.CharField(blank=True, max_length=20, null=True)),
                ('python_impl', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('os_release', models.CharField(blank=True, max_length=50, null=True)),
                ('architecture', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('cwd', models.CharField(blank=True, max_length=300, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReposVisitors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
